[
[
"Sunday_morning",
"Kyoto Jazz Massive",
"Kyoto Jazz Massive feat. Bebel Gilberto - The View From Her Room",
"http://userserve-ak.last.fm/serve/126/365413.jpg",
"2010",
"electro",
"60",
"https://i.ytimg.com/vi/oLlCAHoFd-g/hqdefault.jpg",
"/watch?v=Cg13sl1dIJ0",
"8:25"
],
[
"Sunday_morning",
"Jean-Pierre Como",
"Jean - Pierre Como - When I Fall In Love",
"http://userserve-ak.last.fm/serve/126/387856.png",
"2010",
"jazz",
"35",
"https://i.ytimg.com/vi/pQp5Pz9BiUw/hqdefault.jpg",
"/watch?v=pQp5Pz9BiUw",
"4:56"
],
[
"Sunday_morning",
"Sarah Nemtanu",
"Showcase - Sarah Nemtanu - Avant de mourir - (3/3) - Fnac Paris Montparnasse",
"http://userserve-ak.last.fm/serve/126/60172319.jpg",
"2010",
"classical",
"60",
"https://i.ytimg.com/vi/RUOEA9Xi3Ts/hqdefault.jpg",
"/watch?v=RUOEA9Xi3Ts",
"3:52"
],
[
"Sunday_morning",
"David Arkenstone",
"Diane Arkenstone: The Angels Voice / The Healing Spirit - 2001.",
"http://userserve-ak.last.fm/serve/126/573150.jpg",
"2011",
"pop",
"60",
"https://i.ytimg.com/vi/ss9b8RWBrjA/hqdefault.jpg",
"/watch?v=ss9b8RWBrjA",
"7:07"
],
[
"Sunday_morning",
"Deuter",
"Deuter - Enchanted Summer Night",
"http://userserve-ak.last.fm/serve/126/64824643.jpg",
"2011",
"rock",
"60",
"https://i.ytimg.com/vi/_uQ28e2dv5w/hqdefault.jpg",
"/watch?v=_uQ28e2dv5w",
"8:08"
],
[
"Sunday_morning",
"Piers Faccini",
"Each Wave That Breaks - From Piers Faccini's Album Tearing Sky",
"http://userserve-ak.last.fm/serve/126/36085769.jpg",
"2012",
"rock",
"35",
"https://i.ytimg.com/vi/571Ks_t4nzI/hqdefault.jpg",
"/watch?v=571Ks_t4nzI",
"2:47"
],
[
"Sunday_morning",
"Pink Martini",
"White Christmas, Part 2",
"http://userserve-ak.last.fm/serve/126/57526497.png",
"2010",
"electro",
"60",
"https://i.ytimg.com/vi/1A205sUUXWE/hqdefault.jpg",
"/watch?v=1A205sUUXWE",
"3:33"
],
[
"Sunday_morning",
"Coldplay",
"Coldplay - Up With the Birds",
"http://userserve-ak.last.fm/serve/126/75646980.png",
"2011",
"rock",
"60",
"https://i.ytimg.com/vi/Fr0ecSWIG-k/hqdefault.jpg",
"/watch?v=Fr0ecSWIG-k",
"3:46"
],
[
"Sunday_morning",
"Scott DuBois",
"Scott DuBois - Illinois Procession Rain",
"-",
"2010",
"jazz",
"35",
"https://i.ytimg.com/vi/Acx0AS0JRKs/hqdefault.jpg",
"/watch?v=Acx0AS0JRKs",
"4:27"
],
[
"Sunday_morning",
"Manu KatchÃƒÂ©",
"Fink at Manu KatchÃƒÆ’Ã‚Â© - Pretty Little Thing (Live)",
"http://userserve-ak.last.fm/serve/126/2857462.jpg",
"2010",
"jazz",
"35",
"https://i.ytimg.com/vi/f-MC7QeYPDI/hqdefault.jpg",
"/watch?v=f-MC7QeYPDI",
"5:49"
],
[
"Sunday_morning",
"Leonard Cohen",
"Leonard Cohen - Going home - mp3 and lyrics from Old ideas 2012",
"http://userserve-ak.last.fm/serve/126/50605937.jpg",
"2012",
"folk",
"60",
"https://i.ytimg.com/vi/mADPDcwEwSw/hqdefault.jpg",
"/watch?v=mADPDcwEwSw",
"3:47"
],
[
"Sunday_morning",
"Roberto Alagna",
"NINNA NANNA - Roberto Alagna",
"http://userserve-ak.last.fm/serve/126/141633.jpg",
"2010",
"vocal pop",
"60",
"https://i.ytimg.com/vi/mNonUogoF3U/hqdefault.jpg",
"/watch?v=mNonUogoF3U",
"3:57"
],
[
"Sunday_morning",
"The Two",
"THE TWO - I Wanna Be With You Again",
"http://userserve-ak.last.fm/serve/126/86065819.jpg",
"2010",
"rock",
"60",
"https://i.ytimg.com/vi/NBxYQyxKT5A/hqdefault.jpg",
"/watch?v=NBxYQyxKT5A",
"4:30"
],
[
"Sunday_morning",
"Jack DeJohnette",
"Jack DeJohnette.Enter Here.",
"http://userserve-ak.last.fm/serve/126/47835207.png",
"2012",
"jazz",
"35",
"https://i.ytimg.com/vi/S7BqYezckYM/hqdefault.jpg",
"/watch?v=S7BqYezckYM",
"2:13"
]
]